#!/usr/bin/env bash
# 契约层单源同步脚本，做三件事：
# 1. 从下方 WF8/CMDS 等变量（八条工作流与命令列表的唯一出处）生成四个适配器 stub：
#    CLAUDE.md、CODEBUDDY.md、.codebuddy/rules/deep-study/RULE.mdc、.trae/rules/deep-study.mdc
#    （生成文件带 GENERATED 标记，勿手改——改这里再跑本脚本）；
# 2. 从通用的 .agents/ 派生 CodeBuddy 的专属适配副本（skills + commands）；
# 3. 同步 server/internal/scaffold/assets/——打包进二进制的 harness 工作区脚手架
#    （启动时铺到数据目录上一级，只建缺失不覆盖）。assets 内用无点目录名
#    （agents/ codebuddy/），运行时写盘再还原成 .agents/ .codebuddy/。
# 用法：在仓库根目录执行 scripts/sync-adapters.sh（make build/cross 会自动调用）
set -euo pipefail
cd "$(dirname "$0")/.."

MARKER='<!-- GENERATED by scripts/sync-adapters.sh —— do not edit directly -->'
WF8='导入/导师/费曼/复习/自测/诊断/规划/合并'
WF8_DETAIL='导入 study:import / 导师 study:tutor / 费曼 study:feynman / 复习（纯 UI）/ 自测 study:quiz / 诊断 study:diagnose / 规划 study:plan / 合并 study:merge'
CMDS='`/study:import`、`/study:tutor`、`/study:feynman`、`/study:quiz`、`/study:diagnose`、`/study:plan`、`/study:merge`'

# GNU/BSD sed 兼容的就地替换
sed_i() {
  if sed --version >/dev/null 2>&1; then sed -i "$@"; else sed -i '' "$@"; fi
}

# ---- 1. 生成四个适配器 stub（格式差异保留在各 heredoc，共享内容走变量）----

cat > CLAUDE.md <<'EOF'
# CLAUDE.md

@MARKER@

本仓库是 SmileX-Deep-Study 个人学习系统。**请阅读并严格遵循仓库根目录的 `AGENTS.md`**——它是与 Web UI 共享的权威契约（目录结构、文件格式、读写红线、八条学习工作流）。

要点速览：

- 学习数据全部是纯文件（`data/` 下的 markdown + frontmatter + JSON），可直接读写；
- `cards/*.md` 的 `fsrs:` 块、`review-log.jsonl`、`recall-log.jsonl` 只有 Go 服务端可写，你只读；
- 八条工作流（@WF8@）的完整步骤见 `AGENTS.md`，技能定义在 `.agents/skills/`（SKILL.md 标准格式）；
- 斜杠命令：@CMDS@（`.agents/commands/study/`）；
- 通用 prompt 模板在 `prompts/`，是技能步骤的摘要，细节以 `.agents/skills/` 下 SKILL.md 为准。
EOF

cat > CODEBUDDY.md <<'EOF'
# CODEBUDDY.md

@MARKER@

本仓库是 SmileX-Deep-Study 个人学习系统。**请先完整阅读仓库根目录的 `AGENTS.md` 并严格遵循**——它是与 Web UI 共享的权威契约（目录结构、文件格式、读写红线、八条学习工作流）。

要点速览：

- 学习数据全部是纯文件（`data/` 下的 markdown + frontmatter + JSON），可直接读写；
- `cards/*.md` 的 `fsrs:` 块、`review-log.jsonl`、`recall-log.jsonl` 只有 Go 服务端可写，你只读（建新卡时原样复制全零 fsrs 块除外）；
- 八条工作流（@WF8@）的完整步骤见 `AGENTS.md`，技能定义在 `.codebuddy/skills/`（或 `.agents/skills/`）；
- 斜杠命令：@CMDS@（`.codebuddy/commands/study/`）；
- 通用 prompt 模板在 `prompts/`，是技能步骤的摘要，细节以 SKILL.md 为准。
EOF

mkdir -p .codebuddy/rules/deep-study .trae/rules

cat > .codebuddy/rules/deep-study/RULE.mdc <<'EOF'
---
description: SmileX-Deep-Study 学习系统数据契约与八条学习工作流（@WF8@）
alwaysApply: true
enabled: true
---
@MARKER@

# SmileX-Deep-Study 学习导师规则

本仓库是个人学习系统。**必须先阅读仓库根目录的 `AGENTS.md` 并严格遵循**——它是与 Web UI 共享的权威契约。

关键红线：

1. 学习数据在 `data/`（纯文件），你可直接读写，但格式必须遵守 AGENTS.md 的 frontmatter 契约。
2. `cards/*.md` 的 `fsrs:` 调度块、`data/progress/review-log.jsonl`、`recall-log.jsonl` 只有 Go 服务端可写，你只读（建新卡时原样复制全零 fsrs 块除外）。
3. 八条工作流的执行步骤以 AGENTS.md 为准：@WF8_DETAIL@。
4. 导师对话坚持苏格拉底式：先提问、给阶梯提示，不直接给答案。
5. 每次会话结束写 `data/sessions/` 日志；修改 mastery.json 必须附 evidence。
EOF

cat > .trae/rules/deep-study.mdc <<'EOF'
---
description: SmileX-Deep-Study 学习系统数据契约与八条学习工作流（@WF8@）
globs:
  - "data/**"
  - "prompts/**"
alwaysApply: true
---
@MARKER@

# SmileX-Deep-Study 学习导师规则

本仓库是个人学习系统。**必须先阅读仓库根目录的 `AGENTS.md` 并严格遵循**——它是与 Web UI 共享的权威契约。

关键红线：

1. 学习数据在 `data/`（纯文件），你可直接读写，但格式必须遵守 AGENTS.md 的 frontmatter 契约。
2. `cards/*.md` 的 `fsrs:` 调度块、`data/progress/review-log.jsonl`、`recall-log.jsonl` 只有 Go 服务端可写，你只读（建新卡时原样复制全零 fsrs 块除外）。
3. 八条工作流的执行步骤以 AGENTS.md 为准：@WF8_DETAIL@。
4. 导师对话坚持苏格拉底式：先提问、给阶梯提示，不直接给答案。
5. 每次会话结束写 `data/sessions/` 日志；修改 mastery.json 必须附 evidence。
EOF

for f in CLAUDE.md CODEBUDDY.md .codebuddy/rules/deep-study/RULE.mdc .trae/rules/deep-study.mdc; do
  sed_i \
    -e "s|@MARKER@|$MARKER|g" \
    -e "s|@WF8_DETAIL@|$WF8_DETAIL|g" \
    -e "s|@WF8@|$WF8|g" \
    -e "s|@CMDS@|$CMDS|g" \
    "$f"
done

# ---- 2. CodeBuddy / WorkBuddy：skills（SKILL.md 格式同源）+ commands（支持 study/ 嵌套 → /study:*）----
rsync -a --delete .agents/skills/    .codebuddy/skills/
rsync -a --delete .agents/commands/  .codebuddy/commands/

# ---- 3. 脚手架资产（go:embed 不能引用包外文件与点开头路径，故需在包内放副本）----
A=server/internal/scaffold/assets
cp AGENTS.md CLAUDE.md CODEBUDDY.md "$A/"
rsync -a --delete .agents/    "$A/agents/"
rsync -a --delete .codebuddy/ "$A/codebuddy/"
rsync -a --delete .trae/      "$A/trae/"
rsync -a --delete roles/      "$A/roles/"
rsync -a --delete prompts/    "$A/prompts/"

echo "已生成四个适配器 stub，同步 .agents/ → .codebuddy/{skills,commands}，并更新 scaffold/assets/"
